name: Build Containers

on:
  workflow_dispatch:
    branches: [ "main" ]
  schedule:
    - cron: '00 1 15 * 0'

concurrency:
  group: build
  cancel-in-progress: true

permissions:
    contents: read
    packages: write
    attestations: write
    id-token: write

jobs:
  build-push:
    runs-on: ubuntu-22.04
    name: Build and push containers
    strategy:
      matrix:
        include:
          - baseimage: "debian:bookworm"
            tags: ["latest", "bookworm"]
          - baseimage: "python:3.13-bookworm"
            tags: ["python", "python-bookworm", "python3.13", "python3.13-bookworm"]
          - baseimage: "python:3.12-bookworm"
            tags: ["python3.12", "python3.12-bookworm"]
    steps:
      - name: Set variables
        id: vars
        run: |
          echo "gh-repo=ghcr.io/${GITHUB_REPOSITORY_OWNER}/raspberrypi-os" >> $GITHUB_OUTPUT
          echo "dh-repo=${GITHUB_REPOSITORY_OWNER}/raspberrypi-os" >> $GITHUB_OUTPUT
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Login to Github Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          pull: true
          platforms: linux/arm64,linux/amd64
          tags: |
            ${{ steps.vars.outputs.gh-repo }}:${{ join(matrix.tags, format(',{0}:', steps.vars.outputs.gh-repo)) }},
            ${{ steps.vars.outputs.dh-repo }}:${{ join(matrix.tags, format(',{0}:', steps.vars.outputs.dh-repo)) }}
          build-args: BASE_CONTAINER=${{ matrix.baseimage }}
          cache-from: type=type=gha
          cache-to: type=gha,mode=max
